Repository HowBaChu/Backend, pull requests merged in 2023-11, with the labels that each got.

#101 [Feature] 회원가입시 상태메시지 입력 제거
  src/main/java/com/HowBaChu/howbachu/domain/dto/member/MemberRequestDto.java
  src/main/java/com/HowBaChu/howbachu/domain/entity/Member.java
Labels: 🔨 Refactor

#102 [Refactor] 신고 대상변경 및 신고정책 추가
  src/main/java/com/HowBaChu/howbachu/domain/constants/ReportCriteria.java
  src/main/java/com/HowBaChu/howbachu/domain/dto/report/ReportResponseDto.java
  src/main/java/com/HowBaChu/howbachu/domain/entity/Member.java
  src/main/java/com/HowBaChu/howbachu/domain/entity/Opin.java
  src/main/java/com/HowBaChu/howbachu/domain/entity/Report.java
  src/main/java/com/HowBaChu/howbachu/domain/entity/embedded/ReportPK.java
  src/main/java/com/HowBaChu/howbachu/exception/constants/ErrorCode.java
  src/main/java/com/HowBaChu/howbachu/repository/ReportRepository.java
  src/main/java/com/HowBaChu/howbachu/service/impl/ReportServiceImpl.java
Labels: 🔨 Refactor

#104 [DOCS] 리드미 1차 작성
  README.md
  docs/README.md
  docs/img/ERD.png
  docs/img/FuncSymbol_blue.png
Labels: 📃 Docs

#105 [Refactor] 전체적인 코드 리팩토링
  src/main/java/com/HowBaChu/howbachu/aop/LoggingAspect.java
  src/main/java/com/HowBaChu/howbachu/config/QuerydslConfig.java
  src/main/java/com/HowBaChu/howbachu/config/RedisConfig.java
  src/main/java/com/HowBaChu/howbachu/config/RedisInitializer.java
  src/main/java/com/HowBaChu/howbachu/controller/AuthController.java
  src/main/java/com/HowBaChu/howbachu/controller/LikesController.java
  src/main/java/com/HowBaChu/howbachu/controller/MemberController.java
  src/main/java/com/HowBaChu/howbachu/controller/OpinController.java
  src/main/java/com/HowBaChu/howbachu/controller/ReportController.java
  src/main/java/com/HowBaChu/howbachu/controller/SearchController.java
  src/main/java/com/HowBaChu/howbachu/controller/TopicController.java
  src/main/java/com/HowBaChu/howbachu/controller/VoteController.java
  src/main/java/com/HowBaChu/howbachu/core/factory/YamlLoadFactory.java
  src/main/java/com/HowBaChu/howbachu/core/manager/AWSFileManager.java
  src/main/java/com/HowBaChu/howbachu/core/manager/FileManager.java
  src/main/java/com/HowBaChu/howbachu/domain/base/BaseEntity.java
  src/main/java/com/HowBaChu/howbachu/domain/constants/MBTI.java
  src/main/java/com/HowBaChu/howbachu/domain/constants/Selection.java
  src/main/java/com/HowBaChu/howbachu/domain/dto/member/StatusResponseDto.java
  src/main/java/com/HowBaChu/howbachu/domain/dto/opin/OpinThreadResponseDto.java
  src/main/java/com/HowBaChu/howbachu/domain/dto/report/ReportRequestDto.java
  src/main/java/com/HowBaChu/howbachu/domain/dto/search/SearchResultResponseDto.java
  src/main/java/com/HowBaChu/howbachu/domain/dto/topic/TopicResponseDto.java
  src/main/java/com/HowBaChu/howbachu/domain/entity/Likes.java
  src/main/java/com/HowBaChu/howbachu/domain/entity/Opin.java
  src/main/java/com/HowBaChu/howbachu/domain/entity/RefreshToken.java
  src/main/java/com/HowBaChu/howbachu/domain/entity/Topic.java
  src/main/java/com/HowBaChu/howbachu/domain/entity/Vote.java
  src/main/java/com/HowBaChu/howbachu/domain/entity/embedded/SubTitle.java
  src/main/java/com/HowBaChu/howbachu/domain/entity/embedded/VotingStatus.java
  src/main/java/com/HowBaChu/howbachu/exception/CustomException.java
  src/main/java/com/HowBaChu/howbachu/exception/constants/ErrorCode.java
  src/main/java/com/HowBaChu/howbachu/jwt/JwtFilter.java
  src/main/java/com/HowBaChu/howbachu/jwt/JwtProvider.java
  src/main/java/com/HowBaChu/howbachu/repository/LikesRepository.java
  src/main/java/com/HowBaChu/howbachu/repository/OpinRepository.java
  src/main/java/com/HowBaChu/howbachu/repository/RefreshTokenRepository.java
  src/main/java/com/HowBaChu/howbachu/repository/Support/Querydsl4RepositorySupport.java
  src/main/java/com/HowBaChu/howbachu/repository/custom/OpinRepositoryCustom.java
  src/main/java/com/HowBaChu/howbachu/repository/custom/TopicRepositoryCustom.java
  src/main/java/com/HowBaChu/howbachu/repository/custom/VoteRepositoryCustom.java
  src/main/java/com/HowBaChu/howbachu/repository/impl/MemberRepositoryImpl.java
  src/main/java/com/HowBaChu/howbachu/repository/impl/OpinRepositoryImpl.java
  src/main/java/com/HowBaChu/howbachu/repository/impl/TopicRepositoryImpl.java
  src/main/java/com/HowBaChu/howbachu/repository/impl/VoteRepositoryImpl.java
  src/main/java/com/HowBaChu/howbachu/service/MailService.java
  src/main/java/com/HowBaChu/howbachu/service/impl/LikesServiceImpl.java
  src/main/java/com/HowBaChu/howbachu/service/impl/MailServiceImpl.java
  src/main/java/com/HowBaChu/howbachu/service/impl/MemberServiceImpl.java
  src/main/java/com/HowBaChu/howbachu/service/impl/OpinServiceImpl.java
  src/main/java/com/HowBaChu/howbachu/service/impl/ReportServiceImpl.java
  src/main/java/com/HowBaChu/howbachu/service/impl/TopicServiceImpl.java
  src/main/java/com/HowBaChu/howbachu/utils/CookieUtil.java
  src/main/java/com/HowBaChu/howbachu/utils/RedisUtil.java
  src/main/java/com/HowBaChu/howbachu/validation/Email/EmailValidator.java
  src/main/java/com/HowBaChu/howbachu/validation/Username/UsernameValidator.java
Labels: 🔨 Refactor

#107 [FIX] 회원 관리 버그 수정
  src/main/java/com/HowBaChu/howbachu/domain/entity/RefreshToken.java
  src/main/java/com/HowBaChu/howbachu/exception/ExceptionHandleFilter.java
  src/main/java/com/HowBaChu/howbachu/jwt/JwtFilter.java
  src/main/java/com/HowBaChu/howbachu/service/impl/MemberServiceImpl.java
  src/main/java/com/HowBaChu/howbachu/validation/Email/EmailValidator.java
Labels: 🐞 BugFix

#110 [Fix] Cookie NP 해결
  src/main/java/com/HowBaChu/howbachu/exception/GlobalExceptionHandler.java
  src/main/java/com/HowBaChu/howbachu/jwt/JwtFilter.java
  src/main/resources/application.yml
Labels: 🐞 BugFix

#111 Feature/#108 opin owner identifier
  src/main/java/com/HowBaChu/howbachu/controller/LikesController.java
  src/main/java/com/HowBaChu/howbachu/controller/OpinController.java
  src/main/java/com/HowBaChu/howbachu/controller/VoteController.java
  src/main/java/com/HowBaChu/howbachu/domain/constants/ResponseCode.java
  src/main/java/com/HowBaChu/howbachu/domain/dto/opin/OpinResponseDto.java
  src/main/java/com/HowBaChu/howbachu/domain/dto/vote/VoteResponseDto.java
  src/main/java/com/HowBaChu/howbachu/domain/entity/Opin.java
  src/main/java/com/HowBaChu/howbachu/repository/OpinRepository.java
  src/main/java/com/HowBaChu/howbachu/repository/custom/OpinRepositoryCustom.java
  src/main/java/com/HowBaChu/howbachu/repository/custom/VoteRepositoryCustom.java
  src/main/java/com/HowBaChu/howbachu/repository/impl/OpinRepositoryImpl.java
  src/main/java/com/HowBaChu/howbachu/repository/impl/VoteRepositoryImpl.java
  src/main/java/com/HowBaChu/howbachu/service/LikesService.java
  src/main/java/com/HowBaChu/howbachu/service/OpinService.java
  src/main/java/com/HowBaChu/howbachu/service/VoteService.java
  src/main/java/com/HowBaChu/howbachu/service/impl/LikesServiceImpl.java
  src/main/java/com/HowBaChu/howbachu/service/impl/MemberServiceImpl.java
  src/main/java/com/HowBaChu/howbachu/service/impl/OpinServiceImpl.java
  src/main/java/com/HowBaChu/howbachu/service/impl/VoteServiceImpl.java
  src/main/resources/application.yml
  src/test/java/com/HowBaChu/howbachu/repository/OpinRepositoryTest.java
Labels: 🐞 BugFix, ✨ Feature, 📬 API, 🔨 Refactor, ✅ Test

#114 [Test] Auth, Member 테스트 코드 리팩토링
  src/main/java/com/HowBaChu/howbachu/config/SecurityConfig.java
  src/main/java/com/HowBaChu/howbachu/controller/MemberController.java
  src/main/java/com/HowBaChu/howbachu/domain/constants/MBTI.java
  src/main/java/com/HowBaChu/howbachu/domain/dto/jwt/TokenDto.java
  src/main/java/com/HowBaChu/howbachu/domain/dto/member/MemberRequestDto.java
  src/main/java/com/HowBaChu/howbachu/domain/entity/Member.java
  src/main/java/com/HowBaChu/howbachu/exception/constants/ErrorCode.java
  src/main/java/com/HowBaChu/howbachu/jwt/JwtFilter.java
  src/main/java/com/HowBaChu/howbachu/service/impl/MailServiceImpl.java
  src/main/java/com/HowBaChu/howbachu/validation/MBTI/MBTIValidator.java
  src/test/java/com/HowBaChu/howbachu/controller/AuthControllerTest.java
  src/test/java/com/HowBaChu/howbachu/controller/MemberControllerTest.java
  src/test/java/com/HowBaChu/howbachu/service/MemberServiceTest.java
Labels: 🔨 Refactor, ✅ Test
