Repository HowBaChu/Backend, pull requests merged in 2023-10, with the labels that each got.

#75 [Feature] member duplicated exception
  src/main/java/com/HowBaChu/howbachu/exception/constants/ErrorCode.java
  src/main/java/com/HowBaChu/howbachu/service/impl/MemberServiceImpl.java
Labels: ✨ Feature, 🔨 Refactor

#82 :sparkles: Opin - Soft Delete 추가.
  src/main/java/com/HowBaChu/howbachu/domain/entity/Opin.java
Labels: ✨ Feature

#83 [Refactor] 유효성 검사 리팩토링
  src/main/java/com/HowBaChu/howbachu/controller/AuthController.java
  src/main/java/com/HowBaChu/howbachu/controller/LikesController.java
  src/main/java/com/HowBaChu/howbachu/controller/MemberController.java
  src/main/java/com/HowBaChu/howbachu/controller/OpinController.java
  src/main/java/com/HowBaChu/howbachu/controller/ReportController.java
  src/main/java/com/HowBaChu/howbachu/controller/SearchController.java
  src/main/java/com/HowBaChu/howbachu/controller/TopicController.java
  src/main/java/com/HowBaChu/howbachu/controller/VoteController.java
  src/main/java/com/HowBaChu/howbachu/domain/constants/MBTI.java
  src/main/java/com/HowBaChu/howbachu/domain/constants/ResponseCode.java
  src/main/java/com/HowBaChu/howbachu/domain/dto/member/MemberRequestDto.java
  src/main/java/com/HowBaChu/howbachu/domain/dto/response/ResResult.java
  src/main/java/com/HowBaChu/howbachu/exception/GlobalExceptionHandler.java
  src/main/java/com/HowBaChu/howbachu/exception/constants/ErrorCode.java
  src/main/java/com/HowBaChu/howbachu/service/impl/MemberServiceImpl.java
  src/main/java/com/HowBaChu/howbachu/validation/Email/EmailValid.java
  src/main/java/com/HowBaChu/howbachu/validation/Email/EmailValidator.java
  src/main/java/com/HowBaChu/howbachu/validation/EnumValidator.java
  src/main/java/com/HowBaChu/howbachu/validation/LimitBound.java
  src/main/java/com/HowBaChu/howbachu/validation/MBTI/MBTIValid.java
  src/main/java/com/HowBaChu/howbachu/validation/MBTI/MBTIValidator.java
  src/main/java/com/HowBaChu/howbachu/validation/Password/PasswordValid.java
  src/main/java/com/HowBaChu/howbachu/validation/Password/PasswordValidator.java
  src/main/java/com/HowBaChu/howbachu/validation/StatusMessage/StatusMessageValid.java
  src/main/java/com/HowBaChu/howbachu/validation/StatusMessage/StatusMessageValidator.java
  src/main/java/com/HowBaChu/howbachu/validation/Username/UsernameValid.java
  src/main/java/com/HowBaChu/howbachu/validation/Username/UsernameValidator.java
Labels: ✨ Feature, 🔨 Refactor

#84 [Feature] Vote Cookie
  src/main/java/com/HowBaChu/howbachu/config/SecurityConfig.java
  src/main/java/com/HowBaChu/howbachu/controller/VoteController.java
  src/main/java/com/HowBaChu/howbachu/jwt/JwtFilter.java
  src/main/java/com/HowBaChu/howbachu/jwt/JwtProvider.java
  src/main/java/com/HowBaChu/howbachu/service/VoteService.java
  src/main/java/com/HowBaChu/howbachu/service/impl/MemberServiceImpl.java
  src/main/java/com/HowBaChu/howbachu/service/impl/VoteServiceImpl.java
  src/main/java/com/HowBaChu/howbachu/utils/CookieUtil.java
Labels: ✨ Feature

#86 [Fix] cors 설정 임시 변경
  src/main/java/com/HowBaChu/howbachu/config/CorsConfig.java
  src/main/java/com/HowBaChu/howbachu/config/SecurityConfig.java
Labels: 🐞 BugFix

#94 [Refactor] Response Entity 펙토리 메소드
  src/main/java/com/HowBaChu/howbachu/controller/AuthController.java
  src/main/java/com/HowBaChu/howbachu/controller/LikesController.java
  src/main/java/com/HowBaChu/howbachu/controller/MemberController.java
  src/main/java/com/HowBaChu/howbachu/controller/OpinController.java
  src/main/java/com/HowBaChu/howbachu/controller/ReportController.java
  src/main/java/com/HowBaChu/howbachu/controller/SearchController.java
  src/main/java/com/HowBaChu/howbachu/controller/TopicController.java
  src/main/java/com/HowBaChu/howbachu/controller/VoteController.java
  src/main/java/com/HowBaChu/howbachu/domain/constants/ResponseCode.java
Labels: 🔨 Refactor
